'use strict';

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('classes').del()
    .then(function () {
      return Promise.all([


//1480982400
//1481068800
//1481155200

        knex('classes').insert({
          id: 1,
          title: 'How to Publish a Successful Blog',
          image_url: 'https://hd.unsplash.com/photo-1452830978618-d6feae7d0ffa',
          date: 'March 8th, 2017',
          unix_timestamp: 1488931200,
          lat: 40.56482200000001,
          lng: -105.12657000000002,
          address: '2618 Somerville Court',
          city: 'Fort Collins',
          state: 'CO',
          zip_code: 80501,
          price: 10,
          description: 'This workshop will cover the fundamentals of blog publishing, from choosing a platform, to choosing topics and preparing articles, to marketing for a specific audience. The final hour will be devoted to workshopping the first article.',
          prerequisites: 'Come with an idea of the topic,  purpose and intended audience for your blog, as well as a rough draft or brainstorm for the first post.',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 6,
          seats_remaining: 3,
          user_id: 5,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 2,
          title: 'Intro to Beat Mixing',
          image_url: 'https://hd.unsplash.com/photo-1470225620780-dba8ba36b745',
          date: 'March 8th, 2017',
          unix_timestamp: 1488931200,
          lat: 40.40402299999999,
          lng: -105.09067600000003,
          address: '972 Winona Circle',
          city: 'Loveland',
          state: 'CO',
          zip_code: 80537,
          price: 10,
          description: 'Today we\'ll focus on learning about how beats are mixed, and the technology needed to do so.',
          prerequisites: 'None',
          start_time: '7:00 p.m.',
          end_time: '8:30 p.m.',
          total_seats: 4,
          seats_remaining: 3,
          user_id: 2,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 3,
          title: 'Brew Your Own Kombucha',
          image_url: 'https://d2v4vjmuxdiocn.cloudfront.net/wp-content/uploads/2015/04/Kombucha.png',
          date: 'March 8th, 2017',
          unix_timestamp: 1488931200,
          lat: 40.013952,
          lng: -105.281769,
          address: '1001 Arapahoe Ave',
          city: 'Boulder',
          state: 'CO',
          zip_code: 80302,
          price: 15,
          description: 'Kombucha is a variety of fermented, lightly effervescent sweetened black or green tea drinks that are commonly intended as functional beverages for their supposed health benefits. It\'s pretty expensive to buy, but can be so cheap to make!',
          prerequisites: 'Nothing is required but an interest in making this healthful and delicious drink! If you\'d like me to pre-order a kombucha starter kit for you ($20), please let me know via message board or private message at least a week before the class.',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 4,
          seats_remaining: 2,
          user_id: 3,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 4,
          title: 'Salsa Dance Lessons',
          image_url: 'http://98441.cdx.c.ooyala.com/41Y3djczqSIyADi4gLvsSgIjSvTi3yW4/promo251658312',
          date: 'March 10th, 2017',
          unix_timestamp: 1489104000,
          lat: 40.1456008,
          lng: -105.09720190000002,
          address: '310 Quail Rd',
          city: 'Longmont',
          state: 'CO',
          zip_code: 80501,
          price: 5,
          description: 'Bring a partner and learn the fundamentals of salsa dancing!',
          prerequisites: 'No dance experience necessary, and all levels welcome!',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 10,
          seats_remaining: 8,
          user_id: 4,
          creation_date: new Date()
        }),


        knex('classes').insert({
          id: 5,
          title: 'Living a Life of Self-Employment',
          image_url: 'https://hd.unsplash.com/photo-1458847462994-d6e8043299f6',
          date: 'March 10th, 2017',
          unix_timestamp: 1489104000,
          address: '623 Denver Ave',
          lat: 40.39670580000001,
          lng: -105.0469349,
          city: 'Loveland',
          state: 'CO',
          zip_code: 80537,
          price: 10,
          description: 'If you\'re tired of working for the man, come listen and learn how to make it on your own. Topics will include how to make your new employment dream a reality, how to quit your present job tactfully, and how to live frugally while you\re figuring it out.',
          prerequisites: 'Job dissatisfaction!',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 5,
          seats_remaining: 2,
          user_id: 9,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 6,
          title: 'Yoga on the Ridge',
          image_url: 'https://hd.unsplash.com/photo-1447452001602-7090c7ab2db3',
          date: 'March 10th, 2017',
          unix_timestamp: 1489104000,
          lat: 39.9947284,
          lng: -105.27967949999999,
          address: 'Chautauqua Trailhead',
          city: 'Boulder',
          state: 'CO',
          zip_code: 80301,
          price: 6,
          description: 'Let\'s do yoga together! This class is for beginner to intermediate students, and will be a fast-paced cardio workout. If we\'re lucky, we\'ll be interrupted by the local deer.',
          prerequisites: 'No prior experience with yoga is necessary! Please remember to bring your own mat, some water, and probably a towel.',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 10,
          seats_remaining: 10,
          user_id: 4,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 7,
          title: 'Parenting: The Good, the Bad, the Ugly',
          image_url: 'https://hd.unsplash.com/photo-1438962136829-452260720431',
          date: 'March 12th, 2017',
          unix_timestamp: 1489276800,
          lat: 40.40760179999999,
          lng: -104.76837669999998,
          address: '5401 W 20th St',
          city: 'Greeley',
          state: 'CO',
          zip_code: 80634,
          price: 15,
          description: 'Are you thinking about becoming a parent, or have one on the way? Come have a candid discussion about the joys and miseries of parenthood, and walk away with plenty of tips and advice. Topics will include feeding, crying, changing diapers, and finding reliable babysitters.',
          prerequisites: null,
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 10,
          seats_remaining: 10,
          user_id: 3,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 8,
          title: 'Sharing Household Chores the Right Way',
          image_url: 'https://hd.unsplash.com/photo-1462475279937-40cb2b162a99',
          date: 'March 12th, 2017',
          unix_timestamp: 1489276800,
          lat: 40.3044771,
          lng: -105.0770291,
          address: '236 Welch Ave',
          city: 'Berthoud',
          state: 'CO',
          zip_code: 80513,
          price: 10,
          description: 'One of the primary causes of relationship distress is the inequitable distribution of household chores. In this class, listen to and be guided by a certified marital and family counselor in developing healthy strategies for distributing duties and handling conflict related to household chores.',
          prerequisites: 'Bring your partner or roommate to this one! Progress is made only when both parties are on board to make changes. Reserving one seat assumes that two people will come for the class.',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 5,
          seats_remaining: 5,
          user_id: 2,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 9,
          title: 'Run Your First 100-miler',
          image_url: 'https://hd.unsplash.com/photo-1456613820599-bfe244172af5',
          date: 'March 12th, 2017',
          unix_timestamp: 1489276800,
          lat: 40.0201222,
          lng: -105.29777539999998,
          address: 'Mount Sanitas Trailhead',
          city: 'Boulder',
          state: 'CO',
          zip_code: 80304,
          price: 10,
          description: 'Learn the fundamentals of training, fueling, and form in preparation for your first ultramarathon of any distance. The class will start with a double-ascent of the Mount Sanitas summit, and end with a question and answer session at the picnic area near the parking lot.',
          prerequisites: 'It is best if you have completed at least a marathon-distance run before beginning to train for an ultramarathon.',
          start_time: '7:00 a.m.',
          end_time: '9:30 a.m.',
          total_seats: 8,
          seats_remaining: 2,
          user_id: 4,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 10,
          title: 'Critically Consuming News',
          image_url: 'https://hd.unsplash.com/photo-1444653614773-995cb1ef9efa',
          date: 'March 14th, 2017',
          unix_timestamp: 1489449600,
          lat: 39.7384326,
          lng: -104.9875409,
          address: '10 W 14th Ave',
          city: 'Denver',
          state: 'CO',
          zip_code: 80204,
          price: 15,
          description: 'With the proliferation of citizen reporting and easy access to information, it has never seemed more important to critically evaluate our sources of information. Take part in this workshop that explains the ideas of purpose, context, and stakeholders, and how these combine to create carefully crafted messages for the public.',
          prerequisites: 'Come with two things printed: An article that you believe has some bias, as well as four or five reader comments written in response to that article. We will analyze these together.',
          start_time: '7:00 a.m.',
          end_time: '8:30 a.m.',
          total_seats: 10,
          seats_remaining: 10,
          user_id: 4,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 11,
          title: 'Intro to Javascript',
          image_url: 'https://hd.unsplash.com/photo-1454165205744-3b78555e5572',
          date: 'March 14th, 2017',
          unix_timestamp: 1489449600,
          lat: 40.588476,
          lng: -105.07421199999999,
          address: ' 242 Linden St',
          city: 'Fort Collins',
          state: 'CO',
          zip_code: 80524,
          price: 15,
          description: 'Are you ready to learn to program? In this course, we will cover basic programming concepts using Javascript, focusing on writing algorithms to solve common programming problems.',
          prerequisites: 'No prior coding knowledge is required to participate. Please bring a computer with a basic text editor downloaded (I recommend Atom) and a willingness to make mistakes and learn!',
          start_time: '5:00 p.m.',
          end_time: '7:30 p.m.',
          total_seats: 8,
          seats_remaining: 4,
          user_id: 5,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 12,
          title: 'Become a Table Tennis Master',
          image_url: 'http://www.allabouttabletennis.com/images/dhs-table-tennis-table.jpg',
          date: 'March 14th, 2017',
          unix_timestamp: 1489449600,
          lat: 40.5316195,
          lng: -105.07841659999997,
          address: '4025 S College Ave',
          city: 'Fort Collins',
          state: 'CO',
          zip_code: 80526,
          price: 20,
          description: 'Come work on skills like defending killer slams, serving unreturnable serves, placing spin at the right moments, and slamming the shit out of the ball. Taught by a four-time national champion and U.S. National Team member.',
          prerequisites: 'Intermediate skill recommended to take full advantage of the advanced concepts and skills that will be taught.',
          start_time: '5:00 p.m.',
          end_time: '7:30 p.m.',
          total_seats: 4,
          seats_remaining: 0,
          user_id: 8,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 13,
          title: 'Advanced Ballroom Dancing',
          image_url: 'http://chicagocityballroom.com/wp-content/uploads/2013/08/Chicago-City-Ballroom.jpg',
          date: 'March 14th, 2017',
          unix_timestamp: 1489449600,
          lat: 40.0057342,
          lng: -105.26344710000001,
          address: '995 Regent Dr',
          city: 'Boulder',
          state: 'CO',
          zip_code: 80302,
          price: 30,
          description: 'Come work on the ballroom dances that interest you most. Each student will receive individualized instruction. The instructor\'s particular expertise includes latin ballroom dances like merengue, tango, salsa and bachata.',
          prerequisites: 'Advanced skill recommended to take full advantage of the advanced concepts and skills that will be taught.',
          start_time: '5:30 p.m.',
          end_time: '8:30 p.m.',
          total_seats: 8,
          seats_remaining: 6,
          user_id: 4,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 14,
          title: 'Football Fundamentals and Appreciation',
          image_url: 'http://i.i.cbsi.com/cnwk.1d/i/tim/2013/02/20/football_620x350.jpg',
          date: 'March 16th, 2017',
          unix_timestamp: 1489622400,
          lat: 39.736051,
          lng: -104.96719259999998,
          address: '1280 Gilpin Street',
          city: 'Denver',
          state: 'CO',
          zip_code: 80218,
          price: 15,
          description: 'Take a few hours to learn about the rules, strategies and stories of football while enjoying the Monday night game! Food will be provided; just bring a notebook, something to drink, and wear the jersey of your favorite team!',
          prerequisites: 'None at all, except for an interest in this violent, violent game.',
          start_time: '6:00 p.m.',
          end_time: '9:00 p.m.',
          total_seats: 6,
          seats_remaining: 6,
          user_id: 1,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 15,
          title: 'English Conversation: Intermediate',
          image_url: 'https://www.english.cam.ac.uk/images/english-video.jpg',
          date: 'March 16th, 2017',
          unix_timestamp: 1489622400,
          lat: 39.7893699,
          lng: -105.02980339999999,
          address: '3333 Regis Blvd',
          city: 'Denver',
          state: 'CO',
          zip_code:  80221,
          price: 20,
          description: 'If you\'re an intermediate level English-language-learner in Denver and want to practice your conversation skills in a focused and guided environment, please join us.',
          prerequisites: ' Our conversation will be focused around a TedTalk that I will find and assign based on student interests expressed through the comment board. So, when you sign up, please add a comment or private message me about your interests!',
          start_time: '9:00 a.m.',
          end_time: '12:00 p.m.',
          total_seats: 3,
          seats_remaining: 3,
          user_id: 6,
          creation_date: new Date()
        }),

        knex('classes').insert({
          id: 16,
          title: 'Cheesemaking Essentials',
          image_url: 'https://www.wisconsincheesemart.com/uploads/dzpro_shop_items/dzpro_shop_item_thumb_image/artisanshippinglogo-jpg.jpg',
          date: 'March 16th, 2017',
          unix_timestamp: 1489622400,
          lat: 39.6402958,
          lng: -104.79212440000003,
          address: '4205 S Buckley Rd',
          city: 'Aurora',
          state: 'CO',
          zip_code:  80013,
          price: 25,
          description: 'Cheesemaking is an art, and the varieties are endless. In this introductory course, we will explore the best methods and conditions for making three types of cheeses.',
          prerequisites: 'Please read the pre-study materials, which include a brief history of cheesemaking and introduction to important terminology. These materials are posted on the comment board, which you will have access to upon signing up for the class.',
          start_time: '6:00 p.m.',
          end_time: '9:00 p.m.',
          total_seats: 6,
          seats_remaining: 6,
          user_id: 6,
          creation_date: new Date()
        }),

        knex.raw('ALTER SEQUENCE classes_id_seq RESTART WITH 17')

      ]);
    });
};
